# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  name: Default

steps:
  - script: |
      ls
      pip install -r requirements.txt
    displayName: 'Install Dependencies'
    workingDirectory: Application

  - script: |
      ls
      python3 -m coverage run -m unittest discover tests/
      python3 -m coverage xml -o coverage-reports/python_cicd_coverage.xml
    displayName: 'Run Tests with Coverage'
    workingDirectory: Application

  - task: SonarCloudPrepare@3
    inputs:
      SonarQube: 'SonarQube Cloud'
      organization: 'azure-devops-sonar-5'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'azure-devops-sonar-5_python-cicd'
      cliProjectName: 'Python-CICD'
      cliSources: '.'
      extraProperties: |
        sonar.projectBaseDir=Application

  - task: SonarCloudAnalyze@3
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'