# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: 1.1$(rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Infra
pr: none

pool:
  name: Default

steps:
  - task: CmdLine@2
    inputs:
      script: |
        ls
        pwd
        cat Infra/requirements.txt
  - task: replacetokens@6
    inputs:
      sources: 'requirements.txt'
      tokenPattern: 'doubleunderscores'
  - task: CmdLine@2
    inputs:
      script: |
        cat Infra/requirements.txt
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'Infra'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/infra.zip'
      replaceExistingArchive: true
    displayName: Zip source code

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Infra'
      publishLocation: 'Container'
    displayName: "Publish artifact"